seed: 85
num_boxes: 2
device: cuda
trainer_hparams:
  batch_size: 256
  epochs: 15
  lr: 1.0e-3
  weight_decay: 1.0e-4
  num_workers: 0
alphazero_iterations: 100
self_play_games_per_iter: 96
optimal_move_cutoff: 6  # 12 moves in total
comparison_games_per_iter: 32
comparison_update_thresh: 0.55
mcts_config:
  n_sim: 100
  c_puct: 2.0
  noise: 0.15
  noise_frac: 0.25
  tau_pi: 1
storage_config:
  buffer_size: 45_000 # 12 * 96 * 5 * 8, retain last 5 iters
  ckpt_dir: ./___ckpt
  exp_name: size2_aug_frank
  augmentation: True
model_config:
  num_filters: 64
  num_res_blocks: 3