seed: 85
num_boxes: 3
# device: mps # not yet implemented
trainer_hparams:
  batch_size: 1024
  epochs: 100
  lr: 3.0e-4
  weight_decay: 0
  num_workers: 0
alphazero_iterations: 100
self_play_games_per_iter: 10
optimal_move_cutoff: 12
comparison_games_per_iter: 20
comparison_update_thresh: 0.5
mcts_config:
  n_sim: 100
  c_puct: 2
  noise: 0.15
  noise_frac: 0.25
  tau_pi: 1
storage_config:
  buffer_size: 2_000
  ckpt_dir: ./___ckpt
  exp_name: score_net_hparam_sweep_informed