# exactly the same as size3_aug_frank.yaml
seed: 85
num_boxes: 3
device: cuda
trainer_hparams:
  batch_size: 256  # trying something smaller
  epochs: 15
  lr: 1.0e-3
  weight_decay: 1.0e-4
  num_workers: 0
alphazero_iterations: 500
self_play_games_per_iter: 96
optimal_move_cutoff: 15  # 24 moves in total
comparison_games_per_iter: 32
comparison_update_thresh: 0.55
mcts_config:
  n_sim: 100
  c_puct: 2.0
  noise: 0.15
  noise_frac: 0.25
  tau_pi: 1
storage_config:
  buffer_size: 90_000 # ~24 * 96 * 5 * 8, retain last 5 iters
  ckpt_dir: ./___ckpt
  exp_name: size3_manyGamesShallowTree_frank
  augmentation: True
model_config:
  num_filters: 64
  num_res_blocks: 4
