seed: 85
num_boxes: 4
device: cuda
trainer_hparams:
  batch_size: 128 # 256?
  epochs: 25 # 15?
  lr: 1.0e-3 # 2.0e-3
  weight_decay: 1.0e-4
  num_workers: 0
alphazero_iterations: 500
self_play_games_per_iter: 64  # 96
optimal_move_cutoff: 24  # 40 moves in total
comparison_games_per_iter: 32
comparison_update_thresh: 0.55
mcts_config:
  n_sim: 200
  c_puct: 2.0
  noise: 0.2 # 0.15?
  noise_frac: 0.25
  tau_pi: 1
storage_config:
  buffer_size: 13_000  # ~40 * 64 * 5, retain last 5 iters # maybe 20_000?
  ckpt_dir: ./___ckpt
  exp_name: size4_exp_frank
model_config: # also change first conv to be 5 by 5?
  num_filters: 64 # 128
  num_res_blocks: 4
